stages:
- sonar
- staging-deploy
- release-package

sonarqube-check:
  stage: sonar
  image: sonarsource/sonar-scanner-cli
  allow_failure: false
  script:
    - sonar-scanner -X -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.projectName=$CI_PROJECT_NAME

staging-deploy:
  stage: staging-deploy
  image: ruby:3.1.0-slim
  before_script:
    - apt-get update -qq && apt-get install -y build-essential -y curl -y openssh-client
    - eval $(ssh-agent -s)  
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - curl -sL https://deb.nodesource.com/setup_16.x | bash - 
    - apt install nodejs
    # Add these lines to install required libraries
    - apt-get install -y libffi-dev 
    - apt-get install -y libssl-dev
  script:
    - npm install
    - bundle install
    - npm run build
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r _site/* $DEST_FOLDER_URL
  only:
  - dev

release-package:  
  stage: release-package
  image: ruby:3.1.0-slim
  before_script:
    - apt-get update -qq && apt-get install -y build-essential -y curl -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null 
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - curl -sL https://deb.nodesource.com/setup_16.x | bash -
    - apt install nodejs
    # Add these lines to install required libraries 
    - apt-get install -y libffi-dev
    - apt-get install -y libssl-dev
  script:
    - npm install
    - bundle install
    - npm ci
    - npm run build:lib
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish --tag latest
  environment: production
  only:
    - dev