# For Jekyll SEO
title: Government Design Component
description-en: >-
  The Government Design Component  was developed to empower teams in creating fast, accessible and mobile-friendly digital services.
description-kh: >-
  យើងធ្វើឱ្យវាកាន់តែងាយស្រួលក្នុងការបង្កើតគេហទំព័ររដ្ឋាភិបាលដែលងាយស្រួលប្រើ និងឆាប់រហ័សក្នុងការបង្កើត។
logo: /assets/img/logo_dgc_rectangle.svg
url: https://rachana.gov.kh/

# Site data
cgds-version: 1.0.0
cgds-package-name: >-
  @dgtdept/rachana
bootstrap-version: 5.1.3

search_placeholder: "What are you looking for?"


#github links
github-link: https://github.com/DGTDept/Rachana
github-cgds-variables: https://github.com/DGTDept/Rachana/blob/dev/sass/_variables.scss
github-changelog: https://github.com/DGTDept/Rachana/blob/dev/CHANGELOG.md

#footer links
report-vulnerability: "https://form.gov.kh/651cea27dc95760012665cbc"
dgc-link: https://wordpress.rachana.gov.kh
mptc-link: https://mptc.gov.kh/
facebook-link: https://www.facebook.com/digitalgovernmentcommittee
youtube-link: https://www.youtube.com/@MPTCMedia
telegram-link: https://t.me/digitalgovernmentcommittee
tiktok-link: https://www.tiktok.com/@dg.committee
linkedin-link: https://www.linkedin.com/company/dgcgovkh/
location: https://www.google.com/maps/place/Ministry+of+Post+and+Telecommunications/@11.5752631,104.9148119,17z/data=!3m1!4b1!4m6!3m5!1s0x31095142eadcf8db:0xbd4e32a5eccddfb7!8m2!3d11.5752631!4d104.9173868!16s%2Fg%2F1yfdrw680?entry=ttu
feedback-form: "https://form.gov.kh/"
bootstrap-version: 5.1.3

#offcanvas link
npm-link: https://www.npmjs.com/package/@dgtdept/rachana

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-toc
  - jekyll-get-json
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

collections_dir: collections
collections:
  components:
    permalink: /:collection/:name
    output: true
    category: components
    order:
      - official-government-banner.html
      - footer.html
      - main-navigation.html
      - side-navigation.html
  patterns:
    permalink: /:collection/:name
    output: true
    category: patterns
  templates:
    permalink: /:collection/:name
    output: true
    category: templates
    order:
      - landing-page.html
      - single-page-form.html
      - multi-page-form.html
  rachana-wordpress:
    permalink: /:collection/:name
    output: true
    category: rachana-wordpress
    order:
      - rachana-theme.html
      - rachana-plugin.html
  get-started:
    permalink: /:collection/:name
    output: true
    category: get-started
    order:
      - installation.html
      - customise-with-sass.html
      - ui-kit.html
      - wp-theme.html
      - wp-plugin.html
      - wp-demo.html
# set all patterns collection to use certain layouts
defaults:
  -
    scope:
      type: "patterns"
    values:
      layout: "layout-sidenav"
      pageCategory: "patterns"
      source-grid: true
      toc: true
  -
    scope:
      type: "components"
    values:
      layout: "layout-sidenav"
      pageCategory: "components"
      source-grid: true
      toc: true
  -
    scope:
      type: "templates"
    values:
      layout: "layout-sidenav"
      pageCategory: "templates"
      source-grid: false
      toc: true
  -
    scope:
      type: "rachana-wordpress"
    values:
      layout: "layout-sidenav"
      pageCategory: "rachana-wordpress"
      source-grid: false
      toc: true
  -
    scope:
      type: "get-started"
    values:
      layout: "layout-sidenav"
      pageCategory: "get-started"
      source-grid: false
      toc: true

exclude:
  - src
  - node_modules
  - build
  - scripts
  - Dockerfile
  - Gemfile*
  - package*.json
  - webpack.config.js
  - Gruntfile.js
  - amplify.yml
  - cgds/cgds.scss
  - cgds/sass

sass:
  sass_dir: assets/custom-css

toc:
  list_id: toc # Default: "toc"
  list_class: toc # Default: "section-nav"
  no_toc_section_class:
    - cgds-example
    - code-snippet
  sublist_class: toc-sublist # Default: no class for sublists
  item_class: toc-item # Default: "toc-entry"
  item_prefix: item- # Default: "toc-":

jekyll_get_json:
  - data: npm-data-prev-ver
    json: 'https://registry.npmjs.org/-/v1/search?text=@dgtdept/rachana'

languages: ['kh', 'en']
exclude_from_localizations: ['javascript', 'images', 'css', 'html']
