# For Jekyll SEO
title: Singapore Government Design System
description: >- # this means to ignore newlines until "baseurl:"
  Design System unites Singapore Government digital services around a common visual language 
  and user experience
url: "https://www.designsystem.gov.sg"
logo: /assets/img/logo_sgds.png

baseurl: ""

sgds-version: 1.3.2
report_vulnerability: 'https://tech.gov.sg/report_vulnerability'
contact_us: 'https://form.gov.sg/forms/govtech/5bc440ac507956000fdbae91'
feedback_form: 'https://form.gov.sg/#!/forms/govtech/5bd12c6668dbe7000fff9ace'
search_placeholder: 'What are you looking for?'

plugins:
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-redirect-from

collections_dir: components
collections:
  standard:
    permalink: /docs/:path/
    output: true
  layouts:
    permalink: /docs/:path/
    output: true
  general:
    permalink: /docs/:path/
    output: true

exclude:
  - apps/src
  - node_modules
  - build
  - scripts
  - Dockerfile
  - Gemfile*
  - package*.json
  - README.md
  - webpack.config.js
  - Gruntfile.js
  - amplify.yml
