# For Jekyll SEO
title: Singapore Government Design System
description: >-
  Design System unites Singapore Government digital services around a common visual language 
  and user experience
logo: /assets/img/logo_sgds.png

# Site data
sgds-version: 1.3.22
report-vulnerability: "https://tech.gov.sg/report_vulnerability"
contact-us: "https://form.gov.sg/forms/govtech/5bc440ac507956000fdbae91"
feedback-form: "https://form.gov.sg/#!/forms/govtech/5bd12c6668dbe7000fff9ace"
request-component: "https://form.gov.sg/6136ea11658bea0012fc9e80"
search_placeholder: "What are you looking for?"
react-storybook: https://1-0-0-dev.dg2jutx9gylat.amplifyapp.com/
github-link: https://github.com/GovTechSG/sgds/tree/2.0.0-dev

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-toc
  - jekyll-get-json
  
collections_dir: collections
collections:
  components:
    permalink: /:collection/:name
    output: true
    category: components
    order:
      - masthead.html

  patterns:
    permalink: /:collection/:name
    output: true
    category: patterns
  templates:
    permalink: /:collection/:name/
    output: true
    category: templates

# set all patterns collection to use certain layouts
defaults:
  -
    scope:
      type: "patterns" 
    values:
      layout: "layout-sidenav"
      pageCategory: "patterns"
      toc: true
  -
    scope:
      type: "components" 
    values:
      layout: "layout-sidenav"
      pageCategory: "components"
      toc: true
  -
    scope:
      type: "templates" 
    values:
      layout: "layout-sidenav"
      pageCategory: "templates"
      toc: true
      
exclude:
  - src
  - node_modules
  - build
  - scripts
  - Dockerfile
  - Gemfile*
  - package*.json
  - README.md
  - webpack.config.js
  - Gruntfile.js
  - amplify.yml
  - sgds/sgds.scss
  - sgds/sass

sass:
  sass_dir: assets/custom-css

toc:
  list_id: toc # Default: "toc"
  list_class: toc # Default: "section-nav"
  no_toc_section_class: 
    - sgds-example
    - code-snippet
  sublist_class: toc-sublist # Default: no class for sublists
  item_class: toc-item # Default: "toc-entry"
  item_prefix: item- # Default: "toc-":
    
jekyll_get_json: 
  - data: npm-data-prev-ver
    json: 'https://registry.npmjs.org/-/v1/search?text=@govtechsg/sgds'