# .github/workflows/deploy.yml

name: Deploy to DigitalOcean

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          bundle install

      - name: Build site
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            rm -rf ${{ secrets.DEST_FOLDER }}/*
            scp -r _site/* ${{ secrets.DEST_FOLDER }}
