name: Deploy to EC2

on:
  pull_request:
    branches:
      # - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          bundle install

      - name: Build site
        run: npm run build

      - name: Debug - Check _site directory
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of _site directory:"
          ls -la _site

      - name: Copy files to EC2 via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "_site/*"
          target: ${{ secrets.DEST_FOLDER }}
          strip_components: 1
